#!/bin/bash

# $1 argument should equal to "--rebuild" to rebuild an image even if it exists
REBUILD_ARG=${1:-do_not_rebuild}

if [ "$REBUILD_ARG" == "--rebuild" ] || [ "$(docker images -q integration-test-image:ubuntu1604 2> /dev/null)" == "" ]; then

    wget -nc https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-root.tar.gz
    cat xenial-server-cloudimg-amd64-root.tar.gz | docker import - xenial-server-cloudimg
    docker build --rm --tag=integration-test-image:ubuntu1604 .
    docker run --rm --privileged -v /:/host integration-test-image:ubuntu1604 /bin/bash -c setup

else
    echo "Using already built integration-test-image:ubuntu1604 image"
fi
