# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nodeconductor.core.fields
import nodeconductor.core.validators
import re
import waldur_ansible.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('name', models.CharField(max_length=150, validators=[nodeconductor.core.validators.validate_name], verbose_name='name')),
                ('uuid', nodeconductor.core.fields.UUIDField()),
                ('file', models.FileField(upload_to=waldur_ansible.models.get_playbook_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaybookParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('name', models.CharField(help_text='Required. 255 characters or fewer. Letters, numbers and _ characters', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+$'), 'Enter a valid name.')])),
                ('is_required', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, help_text='Default argument for this parameter.', max_length=255)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='waldur_ansible.Playbook')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playbookparameter',
            unique_together=set([('playbook', 'name')]),
        ),
    ]
