# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import nodeconductor.core.fields
import nodeconductor.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0050_reset_cloud_spl_quota_limits'),
        ('waldur_ansible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('name', models.CharField(max_length=150, validators=[nodeconductor.core.validators.validate_name], verbose_name='name')),
                ('uuid', nodeconductor.core.fields.UUIDField()),
                ('arguments', nodeconductor.core.fields.JSONField(blank=True, default={}, null=True)),
                ('output', models.TextField(blank=True)),
                ('state', django_fsm.FSMIntegerField(choices=[(3, 'Running'), (4, 'Run Scheduled'), (1, 'OK'), (2, 'Erred')], default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='playbook',
            old_name='file',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='playbookparameter',
            old_name='is_required',
            new_name='required',
        ),
        migrations.AddField(
            model_name='playbook',
            name='entrypoint',
            field=models.CharField(default='main.yml', help_text='The file to execute in a playbook.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='waldur_ansible.Playbook'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Project'),
        ),
    ]
