# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import waldur_ansible.models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_ansible', '0002_add_parameter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=waldur_ansible.models.get_upload_path),
        ),
    ]
